### ISSUE TITLE
error messages in log

### ISSUE THREAD

**Issue by icygame** [davidnewhall/indigo-8channel-relay#11]
[(https://forums.indigodomo.com/viewtopic.php?f=302&t=22924 )]

plugin is generating the following repeating sequence of error messages. Continues after plugin and preference files are deleted, and reinstalled.

```
> Traceback (most recent call last):
>   File "plugin.py", line 129, in runConcurrentThread
>   File "plugin.py", line 351, in set_device_states
> ValueError: invalid literal for int() with base 10: ''
> 
>    8 Channel Network Relay Error   plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
>    8 Channel Network Relay Error   Error in plugin execution runConcurrentThread:

```

when creating a new device the following additional errors appear

`   Error (client)                  _sendClosedConfigUi3() caught exception: LowLevelBadParameterError
   8 Channel Network Relay Error   Error in plugin execution UiClosed3:

Traceback (most recent call last):
  File "plugin.py", line 119, in closedDeviceFactoryUi
  File "plugin.py", line 351, in set_device_states
ValueError: invalid literal for int() with base 10: ''`

**Comment by davidnewhall** [comment]
Hello and thanks for the report!

It'll be a little while before I can dig into this. 

I've seen this error before and it's usually a "messed up" device that can be fixed with a delete.

**Comment by icygame** [comment]
No worries, and as per the parallel forum discussion, I’m pretty sure thats exactly what it is - having found my rogue device all is good again.
